-- 警告：DROP COLUMN 不可逆，执行前确认已有数据库备份。
-- 这些字段的数据从此改为完整保存在 media_contents.t1_annotation（JSONB）里，
-- 不再需要逐字段的PG列。
ALTER TABLE media_contents
  DROP COLUMN IF EXISTS ideology_label,
  DROP COLUMN IF EXISTS ideology_intensity,
  DROP COLUMN IF EXISTS overall_stance,
  DROP COLUMN IF EXISTS core_stance_strength,
  DROP COLUMN IF EXISTS event_heat,
  DROP COLUMN IF EXISTS event_heat_score,
  DROP COLUMN IF EXISTS account_type_hint,
  DROP COLUMN IF EXISTS risk_level,
  DROP COLUMN IF EXISTS risk_types,
  DROP COLUMN IF EXISTS risk_evidence,
  DROP COLUMN IF EXISTS language_style_tags,
  DROP COLUMN IF EXISTS sentiment_label,
  DROP COLUMN IF EXISTS sentiment_score,
  DROP COLUMN IF EXISTS sentiment_primary_emotion,
  DROP COLUMN IF EXISTS emotion_labels,
  DROP COLUMN IF EXISTS keywords,
  DROP COLUMN IF EXISTS summary,
  DROP COLUMN IF EXISTS topic_category,
  DROP COLUMN IF EXISTS topic_subcategory,
  DROP COLUMN IF EXISTS content_purpose_primary,
  DROP COLUMN IF EXISTS public_attitude_group,
  DROP COLUMN IF EXISTS public_attitude_label,
  DROP COLUMN IF EXISTS public_attitude_intensity,
  DROP COLUMN IF EXISTS event_type_label,
  DROP COLUMN IF EXISTS t1_overall_confidence,
  DROP COLUMN IF EXISTS t1_review_reasons,
  DROP COLUMN IF EXISTS t1_failed_modules,
  DROP COLUMN IF EXISTS bend_tactics,
  DROP COLUMN IF EXISTS aigc_type,
  DROP COLUMN IF EXISTS aigc_score,
  DROP COLUMN IF EXISTS need_human_review,
  DROP COLUMN IF EXISTS entities_hint,
  DROP COLUMN IF EXISTS narrative_hint,
  DROP COLUMN IF EXISTS stance_label,
  DROP COLUMN IF EXISTS stance_target,
  DROP COLUMN IF EXISTS t1_model_version;
